version: '3'

services:
  
  db:
    image: 'postgres'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379

  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    image: api_test
    ports:
      - 3000:3000
    volumes:
      - ./:/api_test/
    command: bash -c "bundle exec rake db:migrate &&
                      rm -f tmp/pids/server.pid && 
                      bundle exec rails s -p 3000 -b '0.0.0.0'"
  
  worker:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "bundle exec rake environment resque:work QUEUE=*"
    volumes:
      - ./:/api_test/
volumes:
  redis:
  postgres: